services:
  web:
    image: curtisasral/homepage:latest
    container_name: curtis-homepage
    environment:
      CHECKLIST_PASSWORD: "${CHECKLIST_PASSWORD}"
      CHECKLIST_COOKIE_SECRET: "${CHECKLIST_COOKIE_SECRET}"
      CHECKLIST_COOKIE_SECURE: "true"
    volumes:
      - ./data:/app/data
    networks:
      - appnet

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared-tunnel
    env_file:
      - .env
    command: tunnel --no-autoupdate run --token ${CLOUDFLARE_TUNNEL_TOKEN}
    networks:
      - appnet

networks:
  appnet:
    driver: bridge
